// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID              uuid.UUID
	Username        string
	Email           string
	HashedPassword  string
	FirstName       string
	LastName        string
	PhoneNumber     sql.NullString
	DateOfBirth     sql.NullTime
	Gender          sql.NullString
	ShippingAddress sql.NullString
	BillingAddress  sql.NullString
	CreatedAt       time.Time
	LastLogin       sql.NullTime
	AccountStatus   string
	UserRole        string
	ProfilePicture  sql.NullString
	TwoFactorAuth   bool
}
